Repository wecode-bootcamp-korea/48-2nd-Default-backend, pull requests merged in 2023-08, with the labels that each got.

#1 Feature/setting
  .env.sample
  .gitignore
  app.js
  package-lock.json
  package.json
  src/models/data-source.js
  src/routes/index.js
Labels: 멘토 리뷰 요청

#2 db_migration 작성
  db/.DS_Store
  db/migrations/20230822031253_create_new_locations.sql
  db/migrations/20230822031331_create_new_categories.sql
  db/migrations/20230822031410_create_new_users.sql
  db/migrations/20230822031441_create_new_hosts.sql
  db/migrations/20230822031517_create_new_rooms.sql
  db/migrations/20230822031548_create_new_room_reviews.sql
  db/migrations/20230822031616_create_new_image.sql
  db/migrations/20230822031646_create_new_room_amenities.sql
  db/migrations/20230822031715_create_new_reservations.sql
  db/migrations/20230822031749_create_new_like_lists.sql
  db/migrations/20230822031816_create_new_like_lists.sql
  db/migrations/20230822031816_create_new_room_likes.sql
  package-lock.json
  src/models/data-source.js
  src/routes/index.js
Labels: 멘토 리뷰 요청

#5 [48기 권영경] Fix: 삭제된 data-source, index 추가
  src/models/data-source.js
  src/routes/index.js
Labels: 멘토 리뷰 요청

#6 db migragtion 수정5
  .env.sample
  db/migrations/20230822031816_create_new_like_lists.sql
Labels: 멘토 리뷰 요청

#3 Feature/user signup
  package-lock.json
  src/controllers/user.controller.js
  src/models/user.dao.js
  src/routes/index.js
  src/routes/user.router.js
  src/services/user.service.js
  src/utilities/errorHandle.js
  src/utilities/validator.js
Labels: 멘토 리뷰 요청

#4 유저 로그인 구현
  app.js
  src/controllers/user.controller.js
  src/routes/user.router.js
  src/services/user.service.js
Labels: 멘토 리뷰 요청

#10 유저 인가 구현
  src/utilities/auth.js
Labels: 멘토 리뷰 요청

#9 db column 추가
  db/migrations/20230827092718_create_column_is_paid.sql
Labels: 멘토 리뷰 요청

#8 Feature/payment_list
  src/controllers/payment.controller.js
  src/models/payment.dao.js
  src/routes/index.js
  src/routes/payment.router.js
  src/services/payment.service.js
  src/utilities/auth.js
Labels: 멘토 리뷰 요청

#13 Feature/get room list
  src/controllers/roomController.js
  src/models/queryBuilder.js
  src/models/roomDAO.js
  src/routes/index.js
  src/routes/roomRouter.js
  src/services/roomService.js
Labels: 멘토 리뷰 요청

#14 결제 완료 기능구현
  src/controllers/payment.controller.js
  src/controllers/user.controller.js
  src/models/payment.dao.js
  src/models/roomDAO.js
  src/routes/payment.router.js
  src/services/payment.service.js
Labels: 멘토 리뷰 요청

#16 유저 인가 userdao연동
  src/models/user.dao.js
  src/utilities/auth.js
Labels: 멘토 리뷰 요청

#17 db migration 최종 수정
  db/migrations/20230831015227_create_column_modify_2.sql
Labels: 멘토 리뷰 요청

#12 create Thumb_nails Table
  db/migrations/20230829102210_create_new_Thumb_nails.sql
Labels: 멘토 리뷰 요청

#21 Feature/detailpage end2
  src/controllers/roomdetail.controller.js
  src/models/data-source.js
  src/models/roomdetail.dao.js
  src/routes/index.js
  src/routes/roomdetail.routes.js
  src/services/roomdetail.service.js
Labels: 멘토 리뷰 요청

#15 roomdetail Page up
  src/controllers/romdetail.controller.js
  src/models/data-source.js
  src/models/romdetail.dao.js
  src/routes/index.js
  src/routes/romdetail.routes.js
  src/services/romdetail.service.js
Labels: Conflict 해결 요청, 수정 요청

#7 Feature/reservations
  db/migrations/20230822031646_create_new_room_amenities.sql
  db/migrations/20230822031715_create_new_reservations.sql
  src/controllers/reservation.controller.js
  src/models/reservation.dao.js
  src/routes/index.js
  src/routes/reservation.router.js
  src/services/reservation.service.js
  src/utilities/auth.js
Labels: 수정 요청
